version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "4321:5432"
    volumes:
      - /Users/mstoczkowski/data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /Users/mstoczkowski/data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge